# Generated by Django 5.0.3 on 2024-03-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_registermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='us_id',
        ),
    ]
