# Generated by Django 5.0.3 on 2024-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
