# Generated by Django 5.0.3 on 2024-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ueser_id',
            field=models.IntegerField(default=0),
        ),
    ]
