# Generated by Django 5.0.3 on 2024-03-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_exercise_ueser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ueser_id',
            new_name='user_id',
        ),
    ]
