# Generated by Django 5.0.3 on 2024-03-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_alter_weight_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Exersize',
            new_name='Exercise',
        ),
        migrations.AddField(
            model_name='weight',
            name='reps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weights.reps'),
        ),
    ]
