# Generated by Django 5.0.3 on 2024-03-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0003_reps_rename_exersize_exercise_weight_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weights.weight'),
        ),
    ]
