# Generated by Django 5.0.3 on 2024-03-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0004_alter_exercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weights',
            field=models.ManyToManyField(related_name='exercises', to='weights.weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='reps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weights.reps'),
        ),
    ]
